# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kzQl0cEnfN7bYisgN-h1Ydbk7I45s1Jq
"""

pip install streamlit

import streamlit as st
import numpy as np
import joblib

# Load trained model
model = joblib.load("mmx_sales_model.pkl")

distribution = st.slider("Weighted Distribution (%)", 40, 60, 50)
price_ratio = st.slider("Price Ratio", 0.8, 1.2, 1.0, 0.01)
adstock = st.slider("Adstock", 0, 4000, 1000)

# Prepare input (same format as training)
X_input = np.array([[
    distribution,
    price_ratio,
    np.log1p(adstock)
]])

log_sales_pred = model.predict(X_input)[0]
sales_pred = np.expm1(log_sales_pred)

st.metric(
    "Predicted Monthly Sales Volume",
    f"{int(sales_pred):,}"
)